navsat_transform_node:
  ros__parameters:
    frequency: 20.0
    delay: 0.5
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    publish_filtered_gps: false
    use_odometry_yaw: true
    wait_for_datum: false
    use_local_cartesian: false
    broadcast_cartesian_transform: true
    broadcast_cartesian_transform_as_parent_frame: true
    transform_timeout: 0.5

local_ekf_node:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: true
    publish_acceleration: false
    predict_to_current_time: false
    print_diagnostics: true

    map_frame: map
    odom_frame: odom

    base_link_frame: base_link

    # 工作模式: 1. world_frame = odom_frame; 2. world_frame = map_frame 全局坐标系
    # 如果输出世界层是 map_frame，它不会直接发 map -> base_link 给 TF 树用，而是去查现有 odom -> base_link，再反推出 map -> odom
    world_frame: odom
    transform_timeout: 0.5

    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  false, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10